version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dict/Dockerfile
    ports:
      - "5008:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CorsOrigins=https://dict-six-kappa.vercel.app
    restart: unless-stopped