[pytest]
testpaths = .
python_files = *Test.py
python_classes = *Test
python_functions = test_*

# HTML report options
addopts = --html=report.html --self-contained-html -v

# Disable warnings
filterwarnings = ignore::DeprecationWarning
